language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

notifications:
  email: false

script:
  - jdk_switcher use oraclejdk8
  - "mvn clean install -Dmaven.javadoc.skip=true -B -V"
  - jdk_switcher use oraclejdk9
  - "mvn clean install -Dmaven.javadoc.skip=true -B -V"
  - jdk_switcher use oraclejdk10
  - "mvn clean install -Dmaven.javadoc.skip=true -B -V"
  - jdk_switcher use oraclejdk9
  - "mvn clean install -Dforce.java9.compilation=true -Dmaven.javadoc.skip=true -B -V"
  - jdk_switcher use oraclejdk10
  - "mvn clean install -Dforce.java9.compilation=true -Dmaven.javadoc.skip=true -B -V"